bfhl:
  user:
    name: "Rishitha Reddy Errepalli"
    regNo: "22BCT0229"
    email: "rishitha305@gmail.com"
  endpoints:
    generate: "https://bfhldevapigw.healthrx.co.in/hiring/generateWebhook/JAVA"
    submit:   "https://bfhldevapigw.healthrx.co.in/hiring/testWebhook/JAVA"
  storage:
    finalQueryFile: "final_query.sql"
logging:
  level:
    root: INFO
